import 'package:flutter/material.dart';

import '../../../../config/language/locale_keys.g.dart';
import '../../../../config/res/assets.gen.dart';
import '../../../../config/res/config_imports.dart';
import '../../../../core/extensions/text_style_extensions.dart';
import '../../../../core/extensions/widgets/padding_extension.dart';
import '../../../../core/extensions/widgets/sized_box_helper.dart';
import '../../../../core/helpers/arabic_numbers_formatter.dart';
import '../../../../core/helpers/helpers.dart';
import '../../../../core/helpers/input_formatters.dart';
import '../../../../core/helpers/validators.dart';
import '../../../../core/navigation/navigator.dart';
import '../../../../core/widgets/buttons/default_button.dart';
import '../../../../core/widgets/buttons/loading_button.dart';
import '../../../../core/widgets/fields/text_fields/custom_text_field.dart';
import '../../../../core/widgets/fields/text_fields/default_text_field.dart';
import '../../../../core/widgets/fields/text_fields/pin_text_field.dart';
import '../../../../core/widgets/icon_widget.dart';
import '../../../logic/home/presentation/imports/view_imports.dart';
import '../../../register/presentation/imports/view_imports.dart';
import '../../../settings/contact_us/presentation/imports/contact_us_imports.dart';
import '../login_view_controller.dart';

part '../view/login_screen.dart';
part '../view/login_confirm_pin_screen.dart';
part '../widgets/login_body.dart';
part '../widgets/login_forgot_password_footer.dart';
part '../widgets/login_confirm_pin_body.dart';
