include: package:flutter_lints/flutter.yaml

analyzer:
  errors:
    # نخلي أغلب التحذيرات Errors مش مجرد Warnings
    empty_catches: error
    prefer_const_constructors: error
    prefer_final_locals: error
    prefer_final_fields: error
    unnecessary_null_checks: error
    prefer_const_literals_to_create_immutables: error
    parameter_assignments: error
    prefer_relative_imports: error
    unnecessary_this: error

linter:
  rules:
    avoid_print: true
    empty_catches: true
    prefer_const_constructors: true
    prefer_final_locals: true
    prefer_final_fields: true
    unnecessary_null_checks: true
    prefer_const_literals_to_create_immutables: true
    parameter_assignments: false
    prefer_relative_imports: true
    unnecessary_this: true
