include: package:flutter_lints/flutter.yaml

analyzer:
  errors:
    deprecated_member_use: ignore
linter:
  rules:
    avoid_print: true
    empty_catches: true
    prefer_const_constructors: true
    prefer_final_locals: true
    prefer_final_fields: true
    unnecessary_null_checks: true
    prefer_const_literals_to_create_immutables: true
    parameter_assignments: false
    prefer_relative_imports: true
    unnecessary_this: true
