import 'dart:math' as math;
import 'dart:ui' as ui;

import 'package:easy_localization/easy_localization.dart';
import 'package:fl_chart/fl_chart.dart';
import 'package:flutter/material.dart';
import '../../../../../config/language/locale_keys.g.dart';
import '../../../../../config/res/assets.gen.dart';
import '../../../../../config/res/config_imports.dart';
import '../../../../../core/extensions/text_style_extensions.dart';
import '../../../../../core/extensions/widgets/margin_extention.dart';
import '../../../../../core/extensions/widgets/padding_extension.dart';
import '../../../../../core/extensions/widgets/sized_box_helper.dart';
import '../../../../../core/extensions/widgets/sliver_extension.dart';
import '../../../../../core/widgets/buttons/default_button.dart';
import '../../../../../core/widgets/fields/text_fields/default_text_field.dart';
import '../../../../../core/widgets/icon_widget.dart';
import '../../../../../core/widgets/pickers/default_bottom_sheet.dart';
import '../../../../../core/widgets/riyal_price_text.dart';
import '../../../../../core/widgets/custom_messages.dart';
import '../../../../../core/extensions/base_state.dart';
import '../../../../../core/widgets/scaffolds/default_scaffold.dart';
import '../../entity/reports_ui_model.dart';
import '../view_controller/reports_view_controller.dart';

part '../view/reports_screen.dart';
part '../widgets/reports_body.dart';
part '../widgets/reports_period_section.dart';
part '../widgets/reports_summary_card.dart';
part '../widgets/reports_savings_section.dart';
part '../widgets/reports_chart_section.dart';
part '../widgets/reports_fixed_expenses_section.dart';
part '../widgets/reports_comparison_section.dart';
part '../widgets/reports_export_section.dart';
part '../widgets/reports_month_detail_sheet.dart';
