import 'package:flutter/material.dart';
import 'package:flutter/services.dart' as service;
import '../../../config/res/config_imports.dart';
import '../../../core/extensions/context_extension.dart';
import '../../../core/extensions/padding_extension.dart';
import '../../../core/extensions/text_style_extensions.dart';
import '../../../core/navigation/navigator.dart';
import '../../../core/widgets/text_fields/default_text_field.dart';
part '../scaffolds/default_scaffold.dart';
part '../fileds/custom_text_field.dart';
part '../scaffolds/home_scaffold.dart';
