import 'dart:math' as math;

import 'package:easy_localization/easy_localization.dart';
import 'package:flutter/material.dart';
import 'package:flutter_bloc/flutter_bloc.dart';
import 'package:injectable/injectable.dart';

import '../../../../../config/language/languages.dart';
import '../../../../../config/language/locale_keys.g.dart';
import '../../../../../config/res/assets.gen.dart';
import '../../../../../config/res/config_imports.dart';
import '../../../../../core/base_crud/code/domain/base_domain_imports.dart';
import '../../../../../core/base_crud/code/presentation/cubit/base_cubit/async_cubit.dart';
import '../../../../../core/extensions/base_state.dart';
import '../../../../../core/extensions/context_extension.dart';
import '../../../../../core/extensions/text_style_extensions.dart';
import '../../../../../core/extensions/widgets/padding_extension.dart';
import '../../../../../core/extensions/widgets/sized_box_helper.dart';
import '../../../../../core/extensions/widgets/widget_extension.dart';
import '../../../../../core/navigation/navigator.dart';
import '../../../../../core/network/api_endpoints.dart';
import '../../../../../core/shared/cubits/user_cubit/user_cubit.dart';
import '../../../../../core/shared/models/base_model.dart';
import '../../../../../core/widgets/buttons/loading_button.dart';
import '../../../../../core/widgets/custom_messages.dart';
import '../../../../../core/widgets/icon_widget.dart';
import '../../../../../core/widgets/pickers/default_bottom_sheet.dart';
import '../../../../../core/widgets/scaffolds/arrow_widget.dart';
import '../../../../../core/widgets/scaffolds/default_scaffold.dart';
import '../../../../../core/widgets/universal_media/widgets.dart';
import '../../entity/settings_row_spec.dart';
import '../../../change_phone/presentation/imports/view_imports.dart';
import '../../../profile/entity/profile_entity.dart';
import '../../../profile/presentation/imports/profile_view_imports.dart';
import '../view_controllers/settings_screen_view_controller.dart';

part '../view/settings_view.dart';
part '../widgets/settings_body.dart';
part '../widgets/settings_leading_icon.dart';
part '../widgets/settings_chevron_row_widget.dart';
part '../widgets/settings_notification_row_widget.dart';
part '../widgets/settings_background_row_widget.dart';
part '../cubits/lang_cubit.dart';
part '../cubits/notify_cubit.dart';
part '../cubits/delete_account_cubit.dart';
part '../widgets/dialogs/delete_account_model_sheet.dart';
