#!/usr/bin/env bash
# scripts/sync-cursor.sh
# ─────────────────────────────────────────────────────────────────────────
# Generates .cursor/rules/<name>.mdc from .claude/skills/<name>/SKILL.md
# (canonical source) plus .claude/skills/<name>/.cursor.yaml (cursor-only
# metadata: globs / alwaysApply). Also generates paste-able prompts under
# .cursor/prompt/<name>.md for skills listed in PASTEABLE_PROMPTS.
#
# Usage:
#   bash scripts/sync-cursor.sh           # sync all
#   bash scripts/sync-cursor.sh --check   # exits 1 if cursor is out of sync
#   bash scripts/sync-cursor.sh --verbose
# ─────────────────────────────────────────────────────────────────────────
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
CLAUDE_DIR="$REPO_ROOT/.claude/skills"
CURSOR_DIR="$REPO_ROOT/.cursor/rules"
CURSOR_PROMPT_DIR="$REPO_ROOT/.cursor/prompt"

# Skills exposed as paste-able prompts
PASTEABLE_PROMPTS=("feature-prompt")

MODE="sync"
VERBOSE=0

for arg in "$@"; do
  case "$arg" in
    --check)   MODE="check" ;;
    --verbose) VERBOSE=1 ;;
    -h|--help) sed -n '2,17p' "$0"; exit 0 ;;
    *) echo "Unknown argument: $arg" >&2; exit 2 ;;
  esac
done

[[ -d "$CLAUDE_DIR" ]] || { echo "ERROR: $CLAUDE_DIR not found." >&2; exit 1; }

mkdir -p "$CURSOR_DIR" "$CURSOR_PROMPT_DIR"

# ── helpers ──────────────────────────────────────────────────────────────

read_description() {
  awk '
    BEGIN { c = 0 }
    /^---[[:space:]]*$/ { c++; next }
    c == 1 && /^description:/ { sub(/^description:[[:space:]]*/, ""); print; exit }
  ' "$1"
}

read_body() {
  awk '
    BEGIN { c = 0 }
    /^---[[:space:]]*$/ { c++; next }
    c >= 2 { print }
  ' "$1"
}

read_yaml_value() {
  local file="$1"; local key="$2"
  [[ -f "$file" ]] || return
  awk -v key="$key" '
    BEGIN { FS = ":" }
    $1 == key {
      idx = index($0, ":")
      v = substr($0, idx + 1)
      sub(/^[[:space:]]+/, "", v); sub(/[[:space:]]+$/, "", v)
      print v; exit
    }
  ' "$file"
}

build_mdc() {
  local skill_name="$1" src="$2" meta="$3"
  local description globs always_apply body
  description="$(read_description "$src")"
  body="$(read_body "$src")"
  globs="$(read_yaml_value "$meta" globs)"
  always_apply="$(read_yaml_value "$meta" alwaysApply)"
  [[ -z "$description" ]] && echo "WARN: $skill_name has no description" >&2
  {
    echo "---"
    echo "description: $description"
    [[ -n "$globs" ]] && echo "globs: $globs"
    [[ -n "$always_apply" ]] && echo "alwaysApply: $always_apply"
    echo "---"
    echo ""
    printf '%s\n' "$body"
  }
}

build_pasteable() {
  local skill_name="$1" src="$2"
  local body
  body="$(read_body "$src")"
  {
    echo "<!--"
    echo "  AUTO-GENERATED FROM: .claude/skills/$skill_name/SKILL.md"
    echo "  DO NOT EDIT THIS FILE DIRECTLY — your changes will be overwritten on the next"
    echo "  run of scripts/sync-cursor.sh. Edit the canonical SKILL.md instead."
    echo ""
    echo "  Usage in Cursor:"
    echo "    1. Type @ in the chat input"
    echo "    2. Pick this file ($skill_name.md)"
    echo "    3. Fill in any [PLACEHOLDERS] before sending"
    echo "-->"
    echo ""
    printf '%s\n' "$body"
  }
}

# ── main loop ────────────────────────────────────────────────────────────

generated=0; unchanged=0; missing_meta=0; drift_count=0
declare -a drift_names=()

for skill_dir in "$CLAUDE_DIR"/*/; do
  skill_name="$(basename "$skill_dir")"
  src="$skill_dir/SKILL.md"
  meta="$skill_dir/.cursor.yaml"
  out="$CURSOR_DIR/$skill_name.mdc"

  [[ -f "$src" ]] || { echo "  skip  $skill_name (no SKILL.md)" >&2; continue; }
  [[ -f "$meta" ]] || { ((missing_meta++)) || true; }

  new_content="$(build_mdc "$skill_name" "$src" "$meta")"
  existing="$([[ -f "$out" ]] && cat "$out" || echo "")"

  if [[ "$new_content" == "$existing" ]]; then
    ((unchanged++)) || true
    [[ "$VERBOSE" -eq 1 ]] && echo "  same  $skill_name"
    continue
  fi

  ((drift_count++)) || true; drift_names+=("$skill_name")
  if [[ "$MODE" == "check" ]]; then echo "  drift $skill_name"; continue; fi
  printf '%s\n' "$new_content" > "$out"
  ((generated++)) || true
  echo "  sync  $skill_name"
done

# Paste-able prompts
pasteable_generated=0; pasteable_unchanged=0
for skill_name in "${PASTEABLE_PROMPTS[@]}"; do
  src="$CLAUDE_DIR/$skill_name/SKILL.md"
  out="$CURSOR_PROMPT_DIR/${skill_name//-/_}.md"
  [[ -f "$src" ]] || { echo "  warn  paste: $skill_name has no SKILL.md" >&2; continue; }
  new="$(build_pasteable "$skill_name" "$src")"
  if [[ -f "$out" ]] && [[ "$new" == "$(cat "$out")" ]]; then
    ((pasteable_unchanged++)) || true; continue
  fi
  if [[ "$MODE" == "check" ]]; then echo "  drift paste: $skill_name"; ((drift_count++)) || true; continue; fi
  printf '%s\n' "$new" > "$out"
  ((pasteable_generated++)) || true
  echo "  sync  paste: $skill_name → $(basename "$out")"
done

# Prompt README
prompt_readme="$CURSOR_PROMPT_DIR/README.md"
prompt_readme_content="# Cursor Paste-able Prompts

Files in this folder are **auto-generated** by \`scripts/sync-cursor.sh\` from canonical
skills under \`.claude/skills/\`. They exist so Cursor users can paste a workflow prompt
directly into chat (or \`@\`-reference it) instead of relying on auto-attach rules.

## Available prompts

| File | Purpose |
|------|---------|
| \`feature_prompt.md\` | Orchestrate building a feature from Figma → working screen. Fill the inputs (feature name, Figma URL, mode) before pasting. |

## How to use in Cursor

1. Open Cursor's chat (Cmd/Ctrl+L).
2. Type \`@\` and pick the prompt file (e.g. \`feature_prompt.md\`).
3. Replace any \`[PLACEHOLDERS]\` (FEATURE_NAME, FIGMA_URL, etc.) with real values.
4. Send.

## Editing rules

**Never edit these files directly.** Edit the canonical \`.claude/skills/<name>/SKILL.md\`
and run \`bash scripts/sync-cursor.sh\` (or commit — the pre-commit hook handles it).
"
if [[ ! -f "$prompt_readme" ]] || [[ "$prompt_readme_content" != "$(cat "$prompt_readme")" ]]; then
  [[ "$MODE" != "check" ]] && printf '%s' "$prompt_readme_content" > "$prompt_readme"
fi

echo ""
echo "summary:"
echo "  source dir : $CLAUDE_DIR"
echo "  target dir : $CURSOR_DIR"
echo "  unchanged  : $unchanged"

if [[ "$MODE" == "check" ]]; then
  echo "  drift      : $drift_count"
  if [[ "$drift_count" -gt 0 ]]; then
    echo ""
    echo "Cursor rules are out of sync with .claude/skills/." >&2
    echo "Run: bash scripts/sync-cursor.sh" >&2
    exit 1
  fi
  echo "OK — cursor rules are in sync."
  exit 0
fi

echo "  generated  : $generated"
echo "  paste-able : $pasteable_generated written, $pasteable_unchanged unchanged"
echo "  no-meta    : $missing_meta"

# Orphan check
if compgen -G "$CURSOR_DIR/*.mdc" > /dev/null; then
  orphan_count=0; declare -a orphan_names=()
  for mdc in "$CURSOR_DIR"/*.mdc; do
    name="$(basename "$mdc" .mdc)"
    if [[ ! -d "$CLAUDE_DIR/$name" ]]; then
      orphan_names+=("$name")
      ((orphan_count++)) || true
    fi
  done
  if [[ "$orphan_count" -gt 0 ]]; then
    echo ""
    echo "  orphans    : $orphan_count rule(s) with no matching .claude skill:"
    for n in "${orphan_names[@]}"; do echo "               - $n.mdc"; done
    echo "  (these rules are not managed by sync; resolve manually)"
  fi
fi

echo ""
echo "Done."
